name: 'pharma_pipeline'
version: '1.0.0'
config-version: 2

profile: 'pharma_pipeline'

model-paths: ["models"]
seed-paths: ["seeds"]
test-paths: ["tests"]

models:
  pharma_pipeline:
    staging:
      +materialized: view
    intermediate:
      +materialized: view
    mart:
      +materialized: table
